### ISSUE TITLE
demo is down

### ISSUE THREAD

**Issue by a7medo778** [bagisto/vuestorefront#1]
### What is your question / Please describe your issue

hey guys, 
i am exploring how fast is bagisto headless, so pretty pumped for this demo
but it looks down

### What version of bagisto integration are you using?

1.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vivek-webkul** [comment]
Hi @a7medo778 

VSF demo is working now.
https://demo.bagisto.com:2087/
