### ISSUE TITLE
How can I set the API URL ?

### ISSUE THREAD

**Issue by anardil** [bagisto/vuestorefront#2]
### What is your question / Please describe your issue

Hello,

How can I set the API URL ?
When I did the command
`yarn dev `

I've got this error

```
[dev:theme]   at /Applications/MAMP/htdocs/vuestorefront/node_modules/apollo-client/bundle.umd.js:1483:29
[dev:theme]   at processTicksAndRejections (internal/process/task_queues.js:97:5)
[dev:theme] Error getWishlist:
[dev:theme] Network error: request to https://undefined/graphql failed, reason: getaddrinfo ENOTFOUND undefined
```
I tried to put this in the middleware.config.js:
```
        api: {
          url: 'http://127.0.0.1:8001'
        },
```
But I doesn't work I've got the same error :(
Can you help me, please?

Thank you.

### What version of bagisto integration are you using?

1.3.3

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by vivek-webkul** [comment]
Hi @anardil 

To run the VueStoreFront project you need to configure the Bagisto Headless project for the server end support, configure the same project by using the below link:
[https://github.com/bagisto/headless-ecommerce/tree/v1.3.0](Bagisto Headless Commerce v1.3.0)

Once you install the Bagisto with the headless project, try to hit this URL in your browser: 
**https://your.domain.com/graphql-playground**

After that, you can configure the Vuestorefront project, you will find the .env.example inside the packages/theme directory. Remain this file to .env and can set the **BAGISTO_DOMAIN**
https://github.com/bagisto/vuestorefront/blob/main/packages/theme/.env.example#L1

I hope this will help you to configure the project.
